### PR TITLE
Update lavalink-without-ssl.md

### PR DESCRIPTION
**Pull request by ThnksCJ**
i made a new lavalink and added a domain to my old one

hello darren are we friends?

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
idk lol

**Comment by ThnksCJ** [comment]
can we be friends?

**Comment by DarrenOfficial** [comment]
idk

**Comment by Pump-Codes** [comment]
bruh wut is tis

**Comment by DarrenOfficial** [comment]
idk

**Pull request merged**
