### PR TITLE
Fresh new 2 LavaLink 

### PR DESCRIPTION
**Pull request by anas-ike**
I have add my 2 LavaLink with are public now and full of resources

### CODE REVIEW

**Review by DarrenOfficial — APPROVED** [review]

**Comment by AjieDev** [comment]
lol , do you limit it to 2gb , or dan punch you

**Comment by anas-ike** [comment]
Dan punched and broke my nose 😁😁 soln i will upgrade it to premium dono node or my own vps in probably 3 days

**Comment by AjieDev** [comment]
great, bruh i just got warned from dan, now i just host it on my local lol

**Comment by DarrenOfficial** [comment]
Great, just host it locally' Don't host it on other people infrastructure that you're not paying for; Bandwidth are expensive.

**Comment by anas-ike** [comment]
Hey i moved it to my vps located in indi with unlimited bandwidth 😊 . Thanks

**Pull request merged**
