### PR TITLE
Reopen - My lavalink server is back up after so many days

### PR DESCRIPTION
**Pull request by testbot-github**

### CODE REVIEW

**Comment by MrInternetGitHub** [comment]
image

image

please fix it and add a comment il merge it.

**Comment by testbot-github** [comment]
@MrInternetGitHub I have fixed the issue

Regards,
Math

**Comment by MrInternetGitHub** [comment]
> @MrInternetGitHub I have fixed the issue
> 
> Regards, Math


still down mate
image

**Comment by testbot-github** [comment]
it is just now updated @MrInternetGitHub 
image

**Comment by testbot-github** [comment]
guess it was down before but it is running tho

**Comment by testbot-github** [comment]
mostly cuz of replit restarting all the repls

**Comment by MrInternetGitHub** [comment]
sorry but i cant add lavalinks hosted on replit 
they go down too often

**Comment by testbot-github** [comment]
> sorry but i cant add lavalinks hosted on replit they go down too often

I'm keeping it 24/7 with boost tho

**Comment by testbot-github** [comment]
image

**Comment by testbot-github** [comment]
it was added before also like at the starting of this project. then the domain expired so I didn't get chance to change the domain.
Since I was free in past few days I changed the domain, etc, etc.

**Pull request closed without merging**
