### PR TITLE
timelessnesses's lavalink

### PR DESCRIPTION
**Pull request by timelessnesses**
im back with new server hopefully it always up (systemctl gaming)  
something.host doesn't have asia countries so i choose finland 😭

### CODE REVIEW

**Comment by AikoNee** [comment]
CloludFalre?

**Review by DarrenOfficial — APPROVED** [review]

**Comment by timelessnesses** [comment]
> CloludFalre? 

I don't proxy

**Comment by AikoNee** [comment]
So it's fine as long as you use "Only DNS"?

**Comment by timelessnesses** [comment]
likely

**Pull request merged**
