### PR TITLE
Added my own LavaLink server

### PR DESCRIPTION
**Pull request by MrMasrozYTLIVE**

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
I recommend removing `IRC.mrmasrozytlive.repl.co` because that will become invalid soon, since if you assign additional domain on replit the repl.co will not work anymore

**Comment by MrMasrozYTLIVE** [comment]
right now domain still connecting using CloudFlare so atm it dont work

**Comment by DarrenOfficial** [comment]
hmm okay then

**Comment by MrMasrozYTLIVE** [comment]
when it connect i'll do new commit and remove that url

**Comment by DarrenOfficial** [comment]
@MrMasrozYTLIVE I just test the lavalink.scpcl.site, but it seems to not works, maybe there's something wrong with your cf firewall rule?
IMG_0632

**Comment by DarrenOfficial** [comment]
this happens both on my pc and on my ovh test machine

**Comment by MrMasrozYTLIVE** [comment]
@DarrenOfficial test now please

**Comment by DarrenOfficial** [comment]
well new error xd
IMG_0633

**Comment by DarrenOfficial** [comment]
make sure your ssl settings is set to either full or flexible. not strict :p
IMG_0634

**Comment by MrMasrozYTLIVE** [comment]
i changed it to flexible and now it works (i think)

**Comment by DarrenOfficial** [comment]
hmm, maybe your repl is missconfigured?

**Comment by MrMasrozYTLIVE** [comment]
Your domain is configured correctly. Linking could take a few minutes. Please don't leave this page.

**Comment by MrMasrozYTLIVE** [comment]
It saying this atm

**Comment by DarrenOfficial** [comment]
> i changed it to flexible and now it works (i think)

well :)
IMG_0635

**Comment by MrMasrozYTLIVE** [comment]
i know. Trying to figure whats wrong now xd

**Comment by DarrenOfficial** [comment]
> Your domain is configured correctly. Linking could take a few minutes. Please don't leave this page.

make sure the orange cloud is turned off when linking the domain. after that's complete you can turn the orange cloud back on

**Comment by MrMasrozYTLIVE** [comment]
wdym?

**Comment by DarrenOfficial** [comment]
this thing, proxy mode. I call this the orange cloud xd
IMG_0636

**Comment by DarrenOfficial** [comment]
make sure it's set to off (orange cloud off) when you're configuring replit to your domain thats on cloudflare
and renable it once the process has completed

**Comment by MrMasrozYTLIVE** [comment]
it should work now

**Comment by DarrenOfficial** [comment]
still brokey

**Comment by MrMasrozYTLIVE** [comment]
strange

**Comment by MrMasrozYTLIVE** [comment]
So i did "https://lavalink.scpcl.site" instead of "lavalink.scpcl.site" and now it saying "Waiting to reach replit through your domain. This can take up to 48 hours. Feel free to check back later."

**Comment by MrMasrozYTLIVE** [comment]
Oh wait. Their site is bugged and there was button lol (Connect domain). Now it should works

**Pull request merged**
