### PR TITLE
Update lavalink-without-ssl.md

### PR DESCRIPTION
**Pull request by HenGPlayZ**

### CODE REVIEW

**Comment by scattyypie** [comment]
chillllllllllllll

**Comment by HenGPlayZ** [comment]
> someone needs to tell this guy what is loadbalancer :D

**Comment by HenGPlayZ** [comment]
All those node's are from different regions and users can decide which regions they want to use. so why should I use load balancer?

**Comment by DarrenOfficial** [comment]
Because load balancer does exactly that. provided you only put number, people will not know from which region it is from anyway

**Pull request merged**
