### PR TITLE
Adding my own lava node :cake:

### PR DESCRIPTION
**Pull request by Kadantte**
Here's my own Lavalink node!

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
https://dpaste.org/hFiT doesn't work.

**Comment by DarrenOfficial** [comment]
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

**Comment by DarrenOfficial** [comment]
Afaik that's because you're using third subdomain https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/limitations/

**Comment by DarrenOfficial** [comment]
you either need to get their advanced certificate manager, or upgrade to business/enterprise, or just turn off cloudflare and just use lets encrypt

**Comment by Kadantte** [comment]
> Afaik that's because you're using third subdomain https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/limitations/

Okay lemme fix that

**Comment by Kadantte** [comment]
```shell
Usui@DESKTOP-P62JFK5 MSYS /e/.dev
$ curl -v --ipv4 https://usui-linku.kadantte.moe
*   Trying 34.120.194.28:443...
* Connected to usui-linku.kadantte.moe (34.120.194.28) port 443 (#0)
* schannel: disabled automatic use of client certificate
* schannel: ALPN, offering http/1.1
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: usui-linku.kadantte.moe
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Length: 0
< Date: Tue, 29 Mar 2022 21:13:16 GMT
< Expect-Ct: max-age=2592000, report-uri="https://sentry.repl.it/api/10/security/?sentry_key=615192fd532445bfbbbe966cd7131791"
< Lavalink-Api-Version: 3
< Replit-Cluster: hacker
<
* Connection #0 to host usui-linku.kadantte.moe left intact
* 
```

**Comment by DarrenOfficial** [comment]
yup that works 👍🏼

**Review by DarrenOfficial — APPROVED** [review]

**Comment by Kadantte** [comment]
Now it's fully sing Cloudflare SSL

```shell
Usui@DESKTOP-P62JFK5 MSYS /e/.dev
$ curl -v --ipv4 https://usui-linku.kadantte.moe
*   Trying 172.67.152.22:443...
* Connected to usui-linku.kadantte.moe (172.67.152.22) port 443 (#0)
* schannel: disabled automatic use of client certificate
* schannel: ALPN, offering http/1.1
* schannel: ALPN, server accepted to use http/1.1
> GET / HTTP/1.1
> Host: usui-linku.kadantte.moe
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Tue, 29 Mar 2022 21:18:28 GMT
< Content-Length: 0
< Connection: keep-alive
< expect-ct: max-age=2592000, report-uri="https://sentry.repl.it/api/10/security/?sentry_key=615192fd532445bfbbbe966cd7131791"
< lavalink-api-version: 3
< replit-cluster: hacker
< CF-Cache-Status: DYNAMIC
< Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=e249UJxNox%2FYlT7CdTaw%2BKwflq8nVMyj58Tpr%2BSxs5lJdqvlHOPYJlPgSHGNUQOLQOwHZnkSZnd7746hkligRpUlqANLnyLLR%2BkQe55fqMdFKE7v2%2FlbSQREZrzBl0ZSs9lrpa3fYM8IaA%3D%3D"}],"group":"cf-nel","max_age":604800}
< NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< Server: cloudflare
< CF-RAY: 6f3ba3622ea8867e-MAD
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
<
* Connection #0 to host usui-linku.kadantte.moe left intact
* 
```

**Pull request merged**
