### PR TITLE
Added 2 servers

### PR DESCRIPTION
**Pull request by testbot-github**

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
If they have the same password, please group them together like https://lavalink-list.darrennathanael.com/location/Europe/ so it doesn't make a whole giant page of the same lavalink thingy

**Review by DarrenOfficial — CHANGES_REQUESTED** [review]
Put it on a single list. i.e lavalink.example.com / lavalink2.example.com

**Comment by testbot-github** [comment]
👍

**Comment by testbot-github** [comment]
@DarrenOfficial

**Comment by DarrenOfficial** [comment]
looks good 👍🏼

**Pull request merged**
