### PR TITLE
RXNationGaming's Lavalink-API Server

### PR DESCRIPTION
**Pull request by RXNationGMG**
Working lavalink server :)

### CODE REVIEW

**Comment by RXNationGMG** [comment]
You can check it if you want tho....

**Comment by AikoNee** [comment]
replit popo

**Comment by DarrenOfficial** [comment]
aint workey
```
curl -I https://lavalink-api.rxnationgaming.cf
HTTP/2 503 
date: Mon, 03 Oct 2022 11:49:32 GMT
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=v6QPNBPFQaOR4XT2aIuHQj2hp7WwRGIt0qFcppBTOyBJqijp3TZJ%2B%2BJV%2Fc5U51CE8NaJf8ifhIbJcpaJACbPvh%2Bryb%2F7bRvuMuusegu1Wi648pTmexJoJexH24Gp34T06WS1elXAxHhaC9EXvmjCTe0zrAIdlrfkBCB4UzM%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 7545747bfdb191ff-FRA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by RXNationGMG** [comment]
> aint workey
> 
> ```
> curl -I https://lavalink-api.rxnationgaming.cf
> HTTP/2 503 
> date: Mon, 03 Oct 2022 11:49:32 GMT
> content-type: text/html; charset=UTF-8
> x-frame-options: SAMEORIGIN
> permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
> cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> expires: Thu, 01 Jan 1970 00:00:01 GMT
> report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=v6QPNBPFQaOR4XT2aIuHQj2hp7WwRGIt0qFcppBTOyBJqijp3TZJ%2B%2BJV%2Fc5U51CE8NaJf8ifhIbJcpaJACbPvh%2Bryb%2F7bRvuMuusegu1Wi648pTmexJoJexH24Gp34T06WS1elXAxHhaC9EXvmjCTe0zrAIdlrfkBCB4UzM%3D"}],"group":"cf-nel","max_age":604800}
> nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
> server: cloudflare
> cf-ray: 7545747bfdb191ff-FRA
> alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
> ```

Ok I'm gonna resolve this

**Comment by DarrenOfficial** [comment]
same thing
```
curl -I http://lavalink-api.rxnationgaming.cf
HTTP/1.1 503 Service Temporarily Unavailable
Date: Mon, 03 Oct 2022 13:30:43 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
X-Frame-Options: SAMEORIGIN
Permissions-Policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=b5%2BgDaxr%2Bau1W4zXGZ42Gxb8EyXyTjKqVoJcDulQD2yt%2BfOgADpmVbHP65AmbdYAPtye4H3UEm7RH1w%2Fl0AVY7XL6J%2BPIFHlH%2FuKaJwiZVma5W3nebav7tJ44XR7CNuu0MLlAqV%2BrZ0uvEJvsK%2F8xUD9iVmHyGz68W0%2B8Ss%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 754608b35c7a9055-FRA
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by MrInternetGitHub** [comment]
is it running on replit free plan?

**Comment by RXNationGMG** [comment]
I'm making some changes on it

**Comment by RXNationGMG** [comment]
Ok I checked it and it seemed worked 200 OK on Without ssl
Screenshot_20221004-123325~2

**Comment by RXNationGMG** [comment]
> is it running on replit free plan?

Nope

**Review by MrInternetGitHub — APPROVED** [review]

**Pull request merged**
