### PR TITLE
Update lavalink-with-ssl.md

### PR DESCRIPTION
**Pull request by Dep0s1t**
Added back my server. 

The previous server got backstabbed by the server provider due to using 20TB of traffic per month.

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
On god?

**Comment by DarrenOfficial** [comment]
Accident, what provider we're u using previously?

**Comment by Dep0s1t** [comment]
> Accident, what provider we're u using previously?

https://www.georgedatacenter.com/

The original owner said he had cancer and sounded like he outsourced the support and maintenance. Then my vm's speed was limited then changed ip for no reason, after that the vm was unstable. so I just stopped using that vm and it's idling until now,

I just checked and can't even connect to the control panel to reinstall the vm.

**Comment by DarrenOfficial** [comment]
ah ic

**Pull request merged**
