### PR TITLE
ADDED LAVALINKS

### PR DESCRIPTION
**Pull request by itzExtinct7**
ADDED LavaLinks 99.9% Uptime

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
IANAL but [99.9](https://uptime.is/99.9) uptime is impossible to reach unless you have redundant DRP and/or multiple loadbalancer.

**Comment by DarrenOfficial** [comment]
and assuming from the free domain that you use [.ml](https://freenom.com) and repl.it hacker plan, you're not gonna reach 99.9% uptime lol

**Comment by itzExtinct7** [comment]
By 99.9% I meant Online 24/7 😂

**Review by DarrenOfficial — APPROVED** [review]

**Comment by DarrenOfficial** [comment]
> By 99.9% I meant Online 24/7 😂

100% uptime? ya sure lmao

**Pull request merged**
