### PR TITLE
24/7 lavalink

### PR DESCRIPTION
**Pull request by 0swian**
Hey,
How do you host your lavalink 24/7?
And if you can help me do it, Please.
I maybe asked it at the wrong place but idk where to, im new.

Thank you

### CODE REVIEW

**Comment by timelessnesses** [comment]
> Hey, How do you host your lavalink 24/7? And if you can help me do it, Please. I maybe asked it at the wrong place but idk where to, im new.
> 
> Thank you

If you have personal server or rent a virtual private server then sure, follow this instruction:  
### Requirement for a server
1. at least 2GB of RAM (this should be added more if you have multiple bots connect to your server)
2. At least 4GB of free disk space (so you can install java 11 or up (i am using openjdk java 19))
3. Good internet connection
### Steps
1. Download JAR file from https://github.com/freyacodes/Lavalink/releases/latest
5. Create `application.yaml` to same place where your JAR file is
6. Copy [this file](https://github.com/freyacodes/Lavalink/blob/master/LavalinkServer/application.yml.example) to `application.yaml`
7. Edit values to your likes
8. Start up your JAR file by `java -jar Lavalink.jar` (I highly recommended you set up the service for this so it will restart automatically)

**Comment by 0swian** [comment]
Than you for you reply

But my problem is not with running a server, the problem is it doesn't stay online and my client always disconnects and reconnects to it. I host it on repl and it doesn't say that it restarts in the console. My client still disconnects and reconnects about every 5 hours.

**Comment by timelessnesses** [comment]
that sucks but you should invest some money if you want your lavalink server stayed up for 24/7  
replit sucks (even hacker subscription) due to  
1. random restarts
2. random ratelimits
3. slow
4. not high performance  
i recommend you to either buy yourself a virtual private server to host it or use other people's lavalink server. most of them are high performance and support multiple sources (like soundcloud or spotify)

**Comment by 0swian** [comment]
Alr Thank you

**Pull request closed without merging**
