### PR TITLE
Update lavalink-without-ssl.md

### PR DESCRIPTION
**Pull request by urfavteddybear**
Removing support for v3, moved to other nodes.

### CODE REVIEW

**Comment by AjieDev** [comment]
HTTP 404 Not Found
----------------------
Details: Failed to validate with code 404 - Not Found


still on v3, still configuring yet?

**Comment by urfavteddybear** [comment]
Still configuring Tunnelbroker, should be up in a bit

**Comment by urfavteddybear** [comment]
There, should be up and running

**Review by AjieDev — APPROVED** [review]
HTTP 200 OK
----------------------
Version: 4.0.7
Java VM Version: 21.0.4
LavaPlayer Version: 2.2.1
Source Managers:
  - soundcloud
  - bandcamp
  - twitch
  - vimeo
  - spotify
  - youtube
  - http
Filters:
  - volume
  - equalizer
  - karaoke
  - timescale
  - tremolo
  - vibrato
  - distortion
  - rotation
  - channelMix
  - lowPass
Plugins:
  - lavasrc-plugin v4.2.0
  - youtube-plugin v1.7.1

**Pull request merged**
