### PR TITLE
Lavalink Hosting

### PR DESCRIPTION
**Pull request by richard1234YT**
### [Uptime](https://uptime.skybloxsystems.com/status/backend)
Version 3

NON SSL versions
Host : 54.36.225.156
Port : 2333
Password : "s4DarqP$&y"
Secure : "false"

Host : 54.36.225.156
Port : 2334
Password : "s4DarqP$&y"
Secure : "false"

Host : 54.36.225.156
Port : 2335
Password : "s4DarqP$&y"
Secure : "false"

SSL versions
Host : lavalink2.skybloxsystems.com
Port : 2333
Password : "s4DarqP$&y"
Secure : "true"

Host : lavalink1.skybloxsystems.com
Port : 2334
Password : "s4DarqP$&y"
Secure : "true"

Host : lavalinkbackup.skybloxsystems.com
Port : 2335
Password : "s4DarqP$&y"
Secure : "true"

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
Hi,

You're pushing to the wrong branch; it should be pointing to the `master`

**Comment by richard1234YT** [comment]
Hi,

It won't allow me to push to master.

**Comment by alfari24** [comment]
Fork repository -> Edit on own repo -> push commit.

I see u fork didn't any changes

**Comment by richard1234YT** [comment]
[Moved to ](https://github.com/DarrenOfficial/lavalink-list/pull/488)

**Comment by richard1234YT** [comment]
Closed, Moved to here [Link](https://github.com/DarrenOfficial/lavalink-list/pull/488)

**Pull request closed without merging**
