### PR TITLE
Added lavalink server

### PR DESCRIPTION
**Pull request by hannesfant**

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
Thankyouu

**Comment by DarrenOfficial** [comment]
Is it at least a fast 1 core, lol

**Comment by hannesfant** [comment]
If it ends up being used enough we'll add more cores to it. No point allocating more cpu time than needed :)
Also, it's got 1gb of ram, no 286mb as your image states, but then again I don't really use lavalink so it might be referring to something else

**Comment by DarrenOfficial** [comment]
Understandable 👍🏼.

It should be enough... for the first week or so.

**Pull request merged**
