### PR TITLE
New lavalink-without-ssl

### PR DESCRIPTION
**Pull request by Dep0s1t**
New lavalink-without-ssl

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
I see that you like waifu

**Comment by Dep0s1t** [comment]
Looks like my copy paste from previous commit didn't end up well. Lmao

**Comment by DarrenOfficial** [comment]
How so?

**Comment by DarrenOfficial** [comment]
also, what did you do to get port 8880 working on cloudflare

**Comment by Dep0s1t** [comment]
> How so?

I think missing ``` at the end

Cloudflare supports http on 8880, you just do like what you normally do with port 443.
You can check ports they support here:
https://www.mondoze.com/guide/kb/which-ports-will-cloudflare-work-with

**Comment by DarrenOfficial** [comment]
> also, what did you do to get port 8880 working on cloudflare

didn't even noticed that lmfao

**Comment by Dep0s1t** [comment]
> > > How so?
> > 
> > 
> > I think missing ``` at the end
> > Cloudflare supports http on 8880, you just do what you normally do with port 443. You can check ports they support here: https://www.mondoze.com/guide/kb/which-ports-will-cloudflare-work-with
> 
> oh ye, https://developers.cloudflare.com/fundamentals/get-started/network-ports I didn't see that 8880 is a thing lmfao

Yep, I love cloudflare. And also waifu, hope you have a nice day.

**Pull request merged**
