### PR TITLE
Update lavalink-without-ssl.md

### PR DESCRIPTION
**Pull request by antivirus786**

### CODE REVIEW

**Comment by antivirus786** [comment]
### Hosted by @ [𝓓𝓔𝓛𝓤𝓢𝓘𝓞𝓝](https://discord.gg/7VQWkeYxS4)
Version 3 | [Uptime Status](status-lavalink.ddns.net:7016/status/bot)
```bash
Host : lavalink.dddns.net
Port : 7106
Password : "discord.gg/FqEQtEtUc9"
Secure : false
```

my lavalink was already added just made some changes in it (port + uptime)

**Review by AjieDev — CHANGES_REQUESTED** [review]
`[Uptime Status](https://status-lavalink.ddns.net:7016/status/bot)`

missing `https://` it will not make it a hyperlink

**Comment by antivirus786** [comment]
i have fixed the issue kindly recheck

**Review by AjieDev — APPROVED** [review]
Status Code: 200 OK
Version:
  - Semantic Version: b0db58a0fd7dcfce4055f0d1f954d19a6f858f12-SNAPSHOT
  - Major: 0
  - Minor: 0
  - Patch: 0
  - Pre-release: null
  - Build: null

Build Time: 1711828199581

Git:
  - Branch: v3-update-lp
  - Commit: b0db58a
  - Commit Time: 1711828121000

JVM Version: 17.0.11

LavaPlayer Version: 0eaeee195f0315b2617587aa3537fa202df07ddc-SNAPSHOT

Source Managers:
  - youtube
  - soundcloud
  - bandcamp
  - twitch
  - vimeo
  - http

Filters:
  - volume
  - equalizer
  - karaoke
  - timescale
  - tremolo
  - vibrato
  - distortion
  - rotation
  - channelMix
  - lowPass

Plugins: None

**Pull request merged**
