### PR TITLE
All These Servers Are Offline For More Than 7 Days

### PR DESCRIPTION
**Pull request by nischay02**
i checked all of these all are offline from more than 7 days and please dont add replit servers here they are useless! from my side i checked and said what i see you can recheck all before accepting the pull all are offline :)

## 1st: lavalink.devin-dev.xyz free railway.app hosted and even online its deleted now
img1

## 2nd: www.lavalink-priyam.ml free replit.com hosted now even working now
img1

## 3rd: lavalink.devz.cloud & lavalink2.devz.cloud both same and now working 
img1

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
god

**Comment by DarrenOfficial** [comment]
I checked pr and make sure they are online.

**Comment by MrMasrozYTLIVE** [comment]
Lie. My server was active day ago and somewhy crashed

**Comment by MrMasrozYTLIVE** [comment]
Bruh. They added limits and my LV hitting limits

**Comment by DarrenOfficial** [comment]
> please dont add replit servers
here's the thing, I have no issue with people making pr for their lavalink server that are hosted on repl.it. as long as they can keep it online and has no "stability" issue.

**Comment by MrMasrozYTLIVE** [comment]
image

**Comment by MrMasrozYTLIVE** [comment]
it working whole days as u can see on my screenshot

**Comment by MrMasrozYTLIVE** [comment]
+ Repl.it nodes works fine. They just did update and to start smthing that hosted on repl.it u need to open it in their editor first as i just saw

**Comment by DarrenOfficial** [comment]
I just noticed that @nischay02 lavalink "freelavalink.ga" is hosted on railway, I would suggest you to not do that because railway "Fair use policy" https://railway.app/legal/fair-use

**Comment by MrMasrozYTLIVE** [comment]
Also nischay02 our (lv node owners) contacts left there is not for joke but for message us if smthing happened to our nodes and we didnt saw it

**Comment by MrMasrozYTLIVE** [comment]
> I just noticed that @nischay02 lavalink "freelavalink.ga" is hosted on railway, I would suggest you to not do that because railway "Fair use policy" https://railway.app/legal/fair-use

lavalink.mariliun.ml is hosted here too
image

**Comment by MrMasrozYTLIVE** [comment]
And 7th is not working too

**Comment by MrMasrozYTLIVE** [comment]
lavalink.eu seems to not work too (atleast for me)

**Comment by MrMasrozYTLIVE** [comment]
disbotlistlavalink.ml is replit and dead. Eh i need to contact their owners lmfao

**Comment by nischay876** [comment]
i know about railway.app TOS i have temporarily hosted there for lake a week more only because i dont want any downtime on my server after a week i have localhosted ubantu server for it :)

**Comment by MrMasrozYTLIVE** [comment]
Contacted Devin about his Node. Going to contact everyone i can find

**Comment by DarrenOfficial** [comment]
https://github.com/DarrenOfficial/lavalink-list#dear-all-lavalink-hosting-owner, I added this in the readme.

**Comment by DarrenOfficial** [comment]
> lavalink.eu seems to not work too (atleast for me)

I've already contacted the owner, he said that it's moved to the subdomain.

**Comment by testbot-github** [comment]
Hey @DarrenOfficial My lavalink servers are working and also there's no website for my lavalink servers so it only works if you connect to the lavalink using a lavalink music bot, etc.

Note - Sometimes someone is ddosing my lavalink servers, so I am trying to fix that.

Regards,
Math

**Comment by DarrenOfficial** [comment]
> Hey @DarrenOfficial My lavalink servers are working and also there's no website for my lavalink servers so it only works if you connect to the lavalink using a lavalink music bot, etc.
> 
> Note - Sometimes someone is ddosing my lavalink servers, so I am trying to fix that.
> 
> Regards, Math

Can you do another pr adding your lavalink back?

--

_Polite as usual_
_Darren_

**Comment by testbot-github** [comment]
> > please dont add replit servers
> 
> here's the thing, I have no issue with people making pr for their lavalink server that are hosted on repl.it. as long as they can keep it online and has no "stability" issue.

Btw I have 24/7 enabled in replit

**Comment by testbot-github** [comment]
> > Hey @DarrenOfficial My lavalink servers are working and also there's no website for my lavalink servers so it only works if you connect to the lavalink using a lavalink music bot, etc.
> > Note - Sometimes someone is ddosing my lavalink servers, so I am trying to fix that.
> > Regards, Math
> 
> Can you do another pr adding your lavalink back?
> 
> --
> 
> _Polite as usual_ _Darren_

Sure, I'll make a pr after I resolve the main node issue

Regards, 
Math

**Comment by nischay876** [comment]
sorry for that but you can use uptimerobot to ping your self when it go down example:
dfdg

**Comment by DarrenOfficial** [comment]
> sorry for that but you can use uptimerobot to ping your self when it go down example:
> dfdg

how many monitors can you use with uptimerobot?

**Comment by nischay876** [comment]
> > sorry for that but you can use uptimerobot to ping your self when it go down example:
> > dfdg
> 
> how many monitors can you use with uptimerobot?

## 50 monitors with 5 min check on free pack
https://uptimerobot.com/pricing/

**Comment by DarrenOfficial** [comment]
k nvm, just gonna stick with freshping

**Comment by nischay876** [comment]
> > please dont add replit servers
> 
> here's the thing, I have no issue with people making pr for their lavalink server that are hosted on repl.it. as long as they can keep it online and has no "stability" issue.

most of the replit servers were using uptimerobot for working 24/7 and with that the lavalink server randomly restarts like 2-3 times a day and who ever would be connected at that time will have to replay the whole song command or playlist

**Comment by testbot-github** [comment]
> sorry for that but you can use uptimerobot to ping your self when it go down example: dfdg

Sure, Lemme try

**Pull request merged**
