### PR TITLE
Update lavalink-without-ssl.md

### PR DESCRIPTION
**Pull request by anas-ike**

### CODE REVIEW

**Review by AjieDev — CHANGES_REQUESTED** [review]
Issue 1
V4 and v3 invalid; same IP and Port

Issue 2
HTTP ERROR 504
Details: Gateway Timeout

**Comment by anas-ike** [comment]
Updated the port to 12634 and 12635 i forgot to update them earlier

**Comment by AjieDev** [comment]
HTTP ERROR 403
Details: Forbidden

**Comment by anas-ike** [comment]
Screenshot_20240811_231806
Pls try again i mistakenly switched application.yml

**Review by AjieDev — APPROVED** [review]

**Comment by AjieDev** [comment]
V3
HTTP 200 OK
gotchu, here's the breakdown for the new one:

**Version Info:**
- *Semantic Version*: 3.7.12
- *Major*: 3
- *Minor*: 7
- *Patch*: 12
- *PreRelease*: null
- *Build*: null

**Build Info:**
- *Build Time*: 1714942683871

**Git Info:**
- *Branch*: HEAD
- *Commit*: 98115f4
- *Commit Time*: 1714941782000

**JVM Version**: 17.0.12

**LavaPlayer Version**: 1.5.4

**Source Managers:**
- youtube
- soundcloud
- bandcamp
- twitch
- vimeo
- local
- spotify
- applemusic
- deezer
- yandexmusic
- youtube (again)
- getyarn.io
- clypit
- speak
- pornhub
- reddit
- ocremix
- tiktok
- mixcloud
- soundgasm
- http

**Filters:**
- volume
- equalizer
- karaoke
- timescale
- tremolo
- vibrato
- distortion
- rotation
- channelMix
- lowPass
- echo
- reverb

**Plugins:**
- lavasrc: 3.2.10
- lavalink-filter-plugin: 0.0.1
- youtube-plugin: 1.5.2
- DuncteBot-plugin: 1.5.1
- SponsorBlock-Plugin: 2.0.0

V4
HTTP 200 OK
**Version Info:**
- *Semantic Version*: 4.0.7
- *Major*: 4
- *Minor*: 0
- *Patch*: 7
- *PreRelease*: 

**Build Info:**
- *Build Time*: 1720476857034

**Git Info:**
- *Branch*: HEAD
- *Commit*: 93102f8
- *Commit Time*: 1720475342000

**JVM Version**: 17.0.12

**LavaPlayer Version**: 2.2.1

**Source Managers:**
- youtube
- soundcloud
- bandcamp
- twitch
- vimeo
- local
- getyarn.io
- clypit
- speak
- pornhub
- reddit
- ocremix
- tiktok
- mixcloud
- soundgasm
- spotify
- applemusic
- deezer
- yandexmusic
- flowery-tts
- youtube (again)
- http

**Filters:**
- volume
- equalizer
- karaoke
- timescale
- tremolo
- vibrato
- distortion
- rotation
- channelMix
- lowPass
- echo
- reverb

**Plugins:**
- lavasearch-plugin: 1.0.0
- sponsorblock-plugin: 3.0.0
- DuncteBot-plugin: 1.6.3
- lavalink-filter-plugin: 0.0.1
- lavasrc-plugin: 4.0.0
- youtube-plugin: 1.5.2
- jiosaavn-plugin: 0.1.7
- java-lyrics-plugin: 1.6.0

**Pull request merged**
