### PR TITLE
Update lavalink-with-ssl.md

### PR DESCRIPTION
**Pull request by chiquidev**

### CODE REVIEW

**Comment by DarrenOfficial** [comment]
I am unable to merge this as all the "nodes" you're trying to add are on Replit free tier. https://dpaste.org/9MsC4
I've accepted https://github.com/DarrenOfficial/lavalink-list/pull/87 because that lavalink is running on Replit hacker plan/cluster.

**Comment by chiquidev** [comment]
I used to have a hacker sub as I have the github student pack, but i think it expired... I have 5 nodes locally hosted on a kubernetes cluster, but I don't know if I should open my house's ports to offer my nodes...

**Comment by DarrenOfficial** [comment]
Just proxy them through a VPS ig

**Comment by chiquidev** [comment]
Wouldn't this affect the speed of the user? Also this will require me to pay a monthly payment and not get it back

**Comment by DarrenOfficial** [comment]
It doesn't. No-one's forcing you to do so...

**Comment by chiquidev** [comment]
hmm sure. And how could I proxy my nodes through a vps? 
I think I can have a vps on digitalocean for free, as I have 100$ credit from github student pack...

**Comment by DarrenOfficial** [comment]
Look up HAProxy, it's a load balancer which you can use to proxy all of your nodes' trough one domain

**Comment by chiquidev** [comment]
cool, tomorroe i'll check it, ty! ;)

**Comment by chiquidev** [comment]
I've locally hosted haproxy to test it, it's going well.. now I just need to install it on a vps and open my home's ports :) image

**Comment by DarrenOfficial** [comment]
👍🏼

**Comment by chiquidev** [comment]
I've successfully install HAProxy on "lavalink.chiquicalris.me" (vps), but I'm in need to redirect "http://lavalink.chiquicalris.me:2305" to my nodes, which uses ssl, how can I do that?

**Comment by DarrenOfficial** [comment]
why are you using ssl?

**Comment by chiquidev** [comment]
I'm using ssl since kubernetes forces me to use https, so I decided to use
cloudflare for the certificate and now to prevent ddos attacks

**Comment by DarrenOfficial** [comment]
Are you on Cloudflare pro or business? If so, then the port needs to be on these specific port https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/.

If you're on Cloudflare free tier, don't use it. The DDoS protection is useless/garbage. It's better to implement rate-limiting on the HAProxy itself. I learned that the hard way lol.
also, Cloudflare adds an additional latency, and random WS disconnect every hour or so.

**Pull request closed without merging**
