### PR TITLE
Update lavalink-without-ssl.md 

### PR DESCRIPTION
**Pull request by anas-ike**
added uptime kuma badges to my LavaLink so it will help users to track its online status and ping.

### CODE REVIEW

**Comment by anas-ike** [comment]
IMG_20240301_050053

**Review by DarrenOfficial — APPROVED** [review]

**Comment by alfari24** [comment]
@anas-ike 
image

**Comment by DarrenOfficial** [comment]
It happens because it's not HTTPS

**Comment by DarrenOfficial** [comment]
image

**Comment by alfari24** [comment]
ah i see, i think that too.


so @anas-ike ask xill to do reverse proxy. if u have domain, set A record to their ip proxy server and give u port server.
and update again with https.

**Comment by DarrenOfficial** [comment]
@anas-ike can you please update from http://hp8.nexcord.com to https://hp8.nexcord.com.proxy.darrenofficial.com

TLS are auto-generated.

Uptime・Ping・Status

**Comment by DarrenOfficial** [comment]
I've reverted this PR until the issue is fixed

**Comment by AjieDev** [comment]
ah let me fix that for you

**Pull request merged**
