### PR TITLE
Update lavalink-with-ssl.md

### PR DESCRIPTION
**Pull request by TFs-INCOGNITO**

### CODE REVIEW

**Comment by MrMasrozYTLIVE** [comment]
Will add it in a sec!

**Comment by MrMasrozYTLIVE** [comment]
Ayo wth bro. It been 2 years

**Comment by DarrenOfficial** [comment]
time flies

**Comment by MrMasrozYTLIVE** [comment]
> time flies

Yeah, that's true, but it sent message after 2 years. It made me laugh

**Pull request merged**
