### PR TITLE
I added one, I found the lavalink server in an another server

### PR DESCRIPTION
**Pull request by testbot-github**

### CODE REVIEW

**Comment by testbot-github** [comment]
Fireball0201 I added ur lavalink server

**Comment by DarrenOfficial** [comment]
@testbot-github remove @Fireball0201 lavalink, It’s already been added.
FB45A397-744B-4E43-9529-438856A42570

**Comment by DarrenOfficial** [comment]
> @testbot-github remove @Fireball0201 lavalink, It’s already been added.
> FB45A397-744B-4E43-9529-438856A42570

there’s no need to add duplicate

**Comment by testbot-github** [comment]
> > @testbot-github remove @Fireball0201 lavalink, It’s already been added.
> > FB45A397-744B-4E43-9529-438856A42570
> 
> there’s no need to add duplicate

sure, lemme remove it. I added an another one other than that

**Comment by testbot-github** [comment]
@DarrenOfficial done, removed the duplicate one

**Pull request merged**
