### PR TITLE
Update lavalink-with-ssl.md

### PR DESCRIPTION
**Pull request by B3ni15**
Hello! I would like to add my lava link. Please check that I wrote everything correctly. Thanks in advance! :D

### CODE REVIEW

**Comment by AjieDev** [comment]
Please remove https

`Host: https://lavalink-v4.huntools-bot.xyz/ `--> `Host: lavalink-v4.huntools-bot.xyz`

**Comment by B3ni15** [comment]
Okay

**Comment by B3ni15** [comment]
Done!

**Review by AjieDev — APPROVED** [review]
HTTP 200 OK
Version:
  - Semantic Version: 4.0.4
  - Major: 4
  - Minor: 0
  - Patch: 4
  - Pre-release: 

Build Time: 1710091930815

Git Information:
  - Branch: HEAD
  - Commit: bb5e126
  - Commit Time: 1710091748000

JVM Version: 17.0.11

LavaPlayer Version: 2.1.1

Source Managers:
  - soundcloud
  - bandcamp
  - twitch
  - vimeo
  - youtube
  - spotify
  - http

Filters:
  - volume
  - equalizer
  - karaoke
  - timescale
  - tremolo
  - vibrato
  - distortion
  - rotation
  - channelMix
  - lowPass

Plugins:
  - Name: youtube-plugin
    Version: e3b83da4eb34899dcf3698e654f78e08acaf06ab
  - Name: lavasrc-plugin
    Version: 4.0.1

**Pull request merged**
