### PR TITLE
change port no ssl

### PR DESCRIPTION
**Pull request by MinazukiAmane**
For the record, you can use 2 ports 80 and 2052, but I suggest 80 as written in the changes

### CODE REVIEW

**Review by AjieDev — APPROVED** [review]

**Comment by AjieDev** [comment]
nah sudah kapok kan ,wkwkwk , jangan lupa HTTPS Rewrite off sama Always HTTPS

**Comment by MinazukiAmane** [comment]
yang meninggal malah v3 nya aowawkaw. btw ratelimit enak di kasih berapa?

**Comment by AjieDev** [comment]
global aja alias /   , pake 5r/10s aja

**Comment by MinazukiAmane** [comment]
dah, asli yg shokaku gila banget, v3 meninggal kena spam. heap ampe kepentok seketika

**Comment by AjieDev** [comment]
emang speknya apaan bisa tewas gitu

**Comment by MinazukiAmane** [comment]
gak kentang kentang amat sih tapi kalau buat hardware mungkin ke itung tua, di thinkstation p700 core nya ku limit di jvm nya jadi 8 malah mokad wkwk

**Comment by DarrenOfficial** [comment]
> yang meninggal malah v3 nya aowawkaw. btw ratelimit enak di kasih berapa?

Throw NGiNX in front of you lavalink & Rate limit it per IP. This is more effective than Cloudflare rate limiting (free plan), and it solves the rapid spam issue.

> https://nginx.org/en/docs/http/ngx_http_limit_conn_module.html

If you use any external firewall (I.e. CiscoIOS, MikroTik, Juniper); note the address, put it in a list and block it 🙂 

If you use software based firewall (I.e. UFW), this also solves the spam issue too.
`ufw insert 1 deny from xx.xx.xx.xx to any comment "spam"`

**Pull request merged**
